// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VsineDual.cpp"
#include "VsineDual___024root__DepSet_hbb9bc171__0.cpp"
#include "VsineDual__Trace__0.cpp"
#include "VsineDual___024root__Slow.cpp"
#include "VsineDual___024root__DepSet_hbb9bc171__0__Slow.cpp"
#include "VsineDual__Syms.cpp"
#include "VsineDual__Trace__0__Slow.cpp"
